In [1]:
import numpy as np
import math

In [2]:
def guassian_elimination(A, b):
    
    #Concontanate the matrix A and right hand side column 
    #vector b into one matrix
    temp_mat = np.c_[A, b]
    
    #Get the number of rows
    n = temp_mat.shape[0]
    
    #Loop over rows
    for i in range(n):
            
        #Find the pivot index by looking down the ith 
        #column from the ith row to find the maximum 
        #(in magnitude) entry.
        p = np.abs(temp_mat[i:, i]).argmax()
            
        #We have to reindex the pivot index to be the 
        #appropriate entry in the entire matrix, not 
        #just from the ith row down.
        p += i 
    
        #Swapping rows to make the maximal entry the 
        #pivot (if needed).
        if p != i:
            temp_mat[[p, i]] = temp_mat[[i, p]]
            
        #Eliminate all entries below the pivot
        factor = temp_mat[i+1:, i] / temp_mat[i, i]
        print(temp_mat)
        print(temp_mat[i+1:, i])
        print(temp_mat[i, i])
        print(factor)
        print(factor[:, np.newaxis])
        print(temp_mat[i])
        print(temp_mat[i+1:])
        print("\n\n")
        temp_mat[i+1:] -= factor[:, np.newaxis] * temp_mat[i]
        
    for i in range(n):
        # Set the pivot column to have 1s along the diagnol
        temp_mat[i] /= temp_mat[i,i]
        
    return temp_mat[:,:n], temp_mat[:,n]

In [3]:
A = np.array([[6.0, -2.0, 2.0, 4.0], [12.0, -8.0, 6.0, 10.0], [3.0, -13.0, 9.0, 3.0], [-6.0, 4.0, 1.0, -18.0]])
b = np.array([[16.0],[26.0],[-19.0], [-34.0]])
A, b = guassian_elimination(A,b)

[[ 12.  -8.   6.  10.  26.]
 [  6.  -2.   2.   4.  16.]
 [  3. -13.   9.   3. -19.]
 [ -6.   4.   1. -18. -34.]]
[ 6.  3. -6.]
12.0
[ 0.5   0.25 -0.5 ]
[[ 0.5 ]
 [ 0.25]
 [-0.5 ]]
[12. -8.  6. 10. 26.]
[[  6.  -2.   2.   4.  16.]
 [  3. -13.   9.   3. -19.]
 [ -6.   4.   1. -18. -34.]]



[[ 12.   -8.    6.   10.   26. ]
 [  0.  -11.    7.5   0.5 -25.5]
 [  0.    2.   -1.   -1.    3. ]
 [  0.    0.    4.  -13.  -21. ]]
[2. 0.]
-11.0
[-0.18181818 -0.        ]
[[-0.18181818]
 [-0.        ]]
[  0.  -11.    7.5   0.5 -25.5]
[[  0.   2.  -1.  -1.   3.]
 [  0.   0.   4. -13. -21.]]



[[ 12.          -8.           6.          10.          26.        ]
 [  0.         -11.           7.5          0.5        -25.5       ]
 [  0.           0.           4.         -13.         -21.        ]
 [  0.           0.           0.36363636  -0.90909091  -1.63636364]]
[0.36363636]
4.0
[0.09090909]
[[0.09090909]]
[  0.   0.   4. -13. -21.]
[[ 0.          0.          0.36363636 -0.90909091 -1.63636364]]



[[

In [4]:
def back_substitution(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = b.size
    x = np.zeros_like(b)

    x[n-1] = b[n-1]/A[n-1, n-1]
    C = np.zeros((n,n))
    for i in range(n-2, -1, -1):
        temp = 0
        for j in range (i+1, n):
            temp += A[i, j]*x[j]
        print(temp)
        C[i, i] = b[i] - temp
        x[i] = C[i, i]/A[i, i]
        print(x)
        print(C)

    return x

In [5]:
x = back_substitution(A,b)
x

-3.2499999999999987
[ 0.  0. -2.  1.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  0.]]
1.318181818181819
[ 0.  1. -2.  1.]
[[ 0.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  0.]]
-0.8333333333333339
[ 3.  1. -2.  1.]
[[ 3.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0. -2.  0.]
 [ 0.  0.  0.  0.]]


array([ 3.,  1., -2.,  1.])

In [6]:
def back_substitution(A, y):
    
    #Number of rows
    n = A.shape[0]
    
    #Allocating space for the solution vector
    x = np.zeros_like(y, dtype=np.double);

    #Here we perform the back-substitution.  
    #Initializing with the last row.
    x[-1] = y[-1] / A[-1, -1]
    print(x)
    #Looping over rows in reverse (from the bottom up), 
    #starting with the second to last row, because the 
    #last row solve was completed in the last step.
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(A[i,i:], x[i:])) / A[i,i]
        print(x)
    return x

In [7]:
x = back_substitution(A,b)
x

[0. 0. 0. 1.]
[ 0.  0. -2.  1.]
[ 0.  1. -2.  1.]
[ 3.  1. -2.  1.]


array([ 3.,  1., -2.,  1.])