In [1]:
import numpy as np
import math

In [2]:
def back_substitution(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = b.size
    x = np.zeros_like(b)

    if A[n-1, n-1] == 0:
        raise ValueError


    x[n-1] = b[n-1]/A[n-1, n-1]
    C = np.zeros((n,n))
    for i in range(n-2, -1, -1):
        bb = 0
        for j in range (i+1, n):
            bb += A[i, j]*x[j]

        C[i, i] = b[i] - bb
        x[i] = C[i, i]/A[i, i]

    return x

In [3]:
x = np.zeros(1)
M = np.matrix([[1, -1, 2], [0, -1, -2], [0, 0, -6]])
c = np.matrix([[0],[0],[3]])
back_substitution(M,c)

matrix([[0],
        [0],
        [0]])

In [4]:
M

matrix([[ 1, -1,  2],
        [ 0, -1, -2],
        [ 0,  0, -6]])

In [5]:
def back_substitution(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    n = b.size
    x = np.zeros_like(b)

    if A[n-1, n-1] == 0:
        raise ValueError

    for i in range(n-1, 0, -1):
        x[i] = A[i, i]/b[i]
        for j in range (i-1, 0, -1):
            A[i, i] += A[j, i]*x[i]

    return x


In [6]:
x = np.zeros(1)
M = np.matrix([[1, -1, 2], [0, -1, -2], [0, 0, -6]])
c = np.matrix([[0],[0],[3]])
back_substitution(M,c)

<ipython-input-5-418a99545c2b>:9: RuntimeWarning: divide by zero encountered in true_divide
  x[i] = A[i, i]/b[i]


matrix([[          0],
        [-2147483648],
        [         -2]])

In [7]:
def lu(A):
    
    #Get the number of rows
    n = A.shape[0]
    
    U = A.copy()
    L = np.eye(n, dtype=np.double)
    
    #Loop over rows
    for i in range(n):
            
        #Eliminate entries below i with row operations 
        #on U and reverse the row operations to 
        #manipulate L
        factor = U[i+1:, i] / U[i, i]
        L[i+1:, i] = factor
        U[i+1:] -= factor[:, np.newaxis] * U[i]
        
    return L, U

In [8]:
def back_substitution(U, y):
    
    #Number of rows
    n = U.shape[0]
    
    #Allocating space for the solution vector
    x = np.zeros_like(y, dtype=np.double);

    #Here we perform the back-substitution.  
    #Initializing with the last row.
    x[-1] = y[-1] / U[-1, -1]
    
    #Looping over rows in reverse (from the bottom up), 
    #starting with the second to last row, because the 
    #last row solve was completed in the last step.
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x


In [9]:
def guassian_elimination(A, b):
    m = np.zeros(A.shape)
    for j in range(A.shape[0]-1):
        for i in range(j+1, A.shape[0]):
            m.itemset((i,j), (A[i,j])/(A[j,j]))
            for k in range(j+1, A.shape[0]):
                A.itemset((i,k), A[i,k] - (m[i,j])*(A[j,k]))
                print(A)
            b.itemset((i,0), b[i,0] - (m[i,j])*(b[j,0]))
    return A, b

In [10]:
M = np.array([[6, -2, 2, 4], [12, -8, 6, 10], [3, -13, 9, 3], [-6, 4, 1, -18]])
c = np.array([[16],[26],[-19], [-34]])
A, b = guassian_elimination(M,c)

[[  6  -2   2   4]
 [ 12  -4   6  10]
 [  3 -13   9   3]
 [ -6   4   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2  10]
 [  3 -13   9   3]
 [ -6   4   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -13   9   3]
 [ -6   4   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   9   3]
 [ -6   4   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   8   3]
 [ -6   4   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   8   1]
 [ -6   4   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   8   1]
 [ -6   2   1 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   8   1]
 [ -6   2   3 -18]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   8   1]
 [ -6   2   3 -14]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   2   1]
 [ -6   2   3 -14]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   2  -5]
 [ -6   2   3 -14]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   2  -5]
 [ -6   2   4 -14]]
[[  6  -2   2   4]
 [ 12  -4   2   2]
 [  3 -12   2  -5]
 [ -6   2   4 -13]]

In [78]:
def guassian_elimination(A, b):
    
    #Concontanate the matrix A and right hand side column 
    #vector b into one matrix
    temp_mat = np.c_[A, b]
    
    #Get the number of rows
    n = temp_mat.shape[0]
    
    #Loop over rows
    for i in range(n):
            
        #Find the pivot index by looking down the ith 
        #column from the ith row to find the maximum 
        #(in magnitude) entry.
        p = np.abs(temp_mat[i:, i]).argmax()
            
        #We have to reindex the pivot index to be the 
        #appropriate entry in the entire matrix, not 
        #just from the ith row down.
        p += i 
    
        #Swapping rows to make the maximal entry the 
        #pivot (if needed).
        if p != i:
            temp_mat[[p, i]] = temp_mat[[i, p]]
            
        #Eliminate all entries below the pivot
        factor = temp_mat[i+1:, i] / temp_mat[i, i]
        print(temp_mat)
        print(temp_mat[i+1:, i])
        print(temp_mat[i, i])
        print(factor)
        print(factor[:, np.newaxis])
        print(temp_mat[i])
        print(temp_mat[i+1:])
        print("\n\n")
        temp_mat[i+1:] -= factor[:, np.newaxis] * temp_mat[i]
        
    for i in range(n):
        # Set the pivot column to have 1s along the diagnol
        temp_mat[i] /= temp_mat[i,i]
        
    return temp_mat[:,:n], temp_mat[:,n], temp_mat

In [79]:
M = np.array([[6.0, -2.0, 2.0, 4.0], [12.0, -8.0, 6.0, 10.0], [3.0, -13.0, 9.0, 3.0], [-6.0, 4.0, 1.0, -18.0]])
c = np.array([[16.0],[26.0],[-19.0], [-34.0]])
A, b, test = guassian_elimination(M,c)

[[ 12.  -8.   6.  10.  26.]
 [  6.  -2.   2.   4.  16.]
 [  3. -13.   9.   3. -19.]
 [ -6.   4.   1. -18. -34.]]
[ 6.  3. -6.]
12.0
[ 0.5   0.25 -0.5 ]
[[ 0.5 ]
 [ 0.25]
 [-0.5 ]]
[12. -8.  6. 10. 26.]
[[  6.  -2.   2.   4.  16.]
 [  3. -13.   9.   3. -19.]
 [ -6.   4.   1. -18. -34.]]



[[ 12.   -8.    6.   10.   26. ]
 [  0.  -11.    7.5   0.5 -25.5]
 [  0.    2.   -1.   -1.    3. ]
 [  0.    0.    4.  -13.  -21. ]]
[2. 0.]
-11.0
[-0.18181818 -0.        ]
[[-0.18181818]
 [-0.        ]]
[  0.  -11.    7.5   0.5 -25.5]
[[  0.   2.  -1.  -1.   3.]
 [  0.   0.   4. -13. -21.]]



[[ 12.          -8.           6.          10.          26.        ]
 [  0.         -11.           7.5          0.5        -25.5       ]
 [  0.           0.           4.         -13.         -21.        ]
 [  0.           0.           0.36363636  -0.90909091  -1.63636364]]
[0.36363636]
4.0
[0.09090909]
[[0.09090909]]
[  0.   0.   4. -13. -21.]
[[ 0.          0.          0.36363636 -0.90909091 -1.63636364]]



[[

In [80]:
A

array([[ 1.        , -0.66666667,  0.5       ,  0.83333333],
       [-0.        ,  1.        , -0.68181818, -0.04545455],
       [ 0.        ,  0.        ,  1.        , -3.25      ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [81]:
b

array([ 2.16666667,  2.31818182, -5.25      ,  1.        ])

In [69]:
print(test)

[[ 12.          -8.           6.          10.          26.        ]
 [  0.         -11.           7.5          0.5        -25.5       ]
 [  0.           0.           4.         -13.         -21.        ]
 [  0.           0.           0.           0.27272727   0.27272727]]


In [ ]:
    #Allocating space for the solution vector
    x = np.zeros_like(b, dtype=np.double);

    #Here we perform the back-substitution.  Initializing 
    #with the last row.
    x[-1] = temp_mat[-1,-1] / temp_mat[-1, -2]
    
    #Looping over rows in reverse (from the bottom up), starting with the second to
    #last row, because the last row solve was completed in the last step.
    for i in range(n-2, -1, -1):
        x[i] = (temp_mat[i,-1] - np.dot(temp_mat[i,i:-1], x[i:])) / temp_mat[i,i]
        
    return x